name: Find Top Research Papers

on:
  schedule:
    # Run at 12:00 AM IST (6:30 AM UTC) every monday and thursday
    - cron: '30 6  * * 1,4'
  workflow_dispatch:  # Allow manual triggering

jobs:
  find-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Find top papers
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST -H "X-API-Key: $API_KEY" "https://recursivai.onrender.com/posts/find_top_papers?num_papers=6"
