name: Call Generate News API

on:
  schedule:
    # Run at 08:00 AM UTC (1:30 PM IST) everyday
    - cron: "0 8 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Generate News API
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-API-Key: $API_KEY" \
            -d '{"days_ago": 2}' \
            "https://recursivai.onrender.com/posts/generate_news"

  send-newsletter:
    needs: call-api
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Wait for Buttondown send window
        run: sleep 1800  # 30 minutes

      - name: Trigger newsletter send
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-API-Key: $API_KEY" \
            -d '{"send": true}' \
            "https://recursivai.onrender.com/newsletter/buttondown"
