name: Call Generate News API

on:
  schedule:
    # Run at 08:00 AM UTC (1:30 PM IST) every Monday and Friday
    - cron: "0 8 * * 1,5"
  workflow_dispatch: # Allow manual triggering

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Generate News API
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"days_ago": 4}' \
          "https://recursivai.onrender.com/posts/generate_news"
